# Generated by Django 4.2.1 on 2023-06-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_contactmodel_contact_alter_contactmodel_pseudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], max_length=100)),
                ('contact', models.CharField(max_length=16)),
                ('matricule', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='ContactModel',
        ),
    ]
