# Generated by Django 4.2.1 on 2023-06-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_contact_delete_contactmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
